
project_id = "gqlkritspnhjxfejvgfg"
[functions.create-daily-room]
verify_jwt = true
[functions."get-availability-settings"]
verify_jwt = true
[functions.create-clinician]
verify_jwt = true
[functions.send-password-reset]
verify_jwt = false
