export const CLIENT_JOURNEY_RPC = {
  fetchAuthenticatedClientContext: 'client_portal_fetch_authenticated_client_context',
  registerClient: 'client_portal_register_client',
  fetchClientReadiness: 'client_portal_fetch_readiness',
  advanceClientIntakeIfReady: 'client_portal_advance_intake_if_ready',
  saveClientInsurance: 'client_portal_save_insurance',
  deleteClientInsurance: 'client_portal_delete_insurance',
  verifyClientInsurance: 'client_portal_verify_insurance',
  fetchInsuranceEligibilityStatus: 'client_portal_fetch_insurance_eligibility',
  acknowledgeInsuranceDeferment: 'client_portal_acknowledge_insurance_deferment',
  fetchMatchableClinicians: 'client_portal_fetch_matchable_clinicians',
  fetchClientWaitState: 'client_portal_fetch_wait_state',
  selectTherapist: 'client_portal_select_therapist',
  fetchActiveTherapistRelationship: 'client_portal_fetch_active_relationship',
  fetchAvailableAppointmentSlots: 'client_portal_fetch_available_slots',
  fetchAppointments: 'client_portal_fetch_appointments',
  bookAppointment: 'client_portal_book_appointment',
  cancelAppointment: 'client_portal_cancel_appointment',
  rescheduleAppointment: 'client_portal_reschedule_appointment',
  fetchPermittedActions: 'client_portal_fetch_permitted_actions',
  requestReactivation: 'client_portal_request_reactivation',
  fetchMessages: 'client_portal_fetch_messages',
  fetchApprovedBillingDisplay: 'client_portal_fetch_approved_billing_display',
} as const;
export type ClientJourneyRpcName = typeof CLIENT_JOURNEY_RPC[keyof typeof CLIENT_JOURNEY_RPC];
