
import { ClientDetails } from '@/types/client';

/**
 * Converts a client profile from auth context to the ClientDetails type
 * expected by components like PHQ9Template
 * 
 * @param clientProfile The client profile from auth context
 * @returns A ClientDetails object that can be used with components
 */
export const convertToClientDetails = (clientProfile: any): ClientDetails => {
  if (!clientProfile) return null;
  
  return {
    id: clientProfile.id,
    client_first_name: clientProfile.client_first_name,
    client_last_name: clientProfile.client_last_name,
    client_preferred_name: clientProfile.client_preferred_name,
    client_email: clientProfile.client_email,
    client_phone: clientProfile.client_phone,
    client_date_of_birth: clientProfile.client_date_of_birth,
    client_age: clientProfile.client_age,
    client_gender: clientProfile.client_gender,
    client_gender_identity: clientProfile.client_gender_identity,
    client_state: clientProfile.client_state,
    client_address: clientProfile.client_address, 
    client_city: clientProfile.client_city, 
    client_zip_code: clientProfile.client_zip_code, 
    client_time_zone: clientProfile.client_time_zone,
    client_minor: clientProfile.client_minor,
    client_status: clientProfile.client_status,
    client_assigned_therapist: clientProfile.client_assigned_therapist,
    client_referral_source: clientProfile.client_referral_source,
    client_self_goal: clientProfile.client_self_goal,
    client_diagnosis: clientProfile.client_diagnosis,
    client_insurance_company_primary: clientProfile.client_insurance_company_primary,
    client_policy_number_primary: clientProfile.client_policy_number_primary,
    client_group_number_primary: clientProfile.client_group_number_primary,
    client_subscriber_name_primary: clientProfile.client_subscriber_name_primary,
    client_insurance_type_primary: clientProfile.client_insurance_type_primary,
    client_subscriber_dob_primary: clientProfile.client_subscriber_dob_primary,
    client_subscriber_relationship_primary: clientProfile.client_subscriber_relationship_primary,
    client_insurance_company_secondary: clientProfile.client_insurance_company_secondary,
    client_policy_number_secondary: clientProfile.client_policy_number_secondary,
    client_group_number_secondary: clientProfile.client_group_number_secondary,
    client_subscriber_name_secondary: clientProfile.client_subscriber_name_secondary,
    client_insurance_type_secondary: clientProfile.client_insurance_type_secondary,
    client_subscriber_dob_secondary: clientProfile.client_subscriber_dob_secondary,
    client_subscriber_relationship_secondary: clientProfile.client_subscriber_relationship_secondary,
    client_insurance_company_tertiary: clientProfile.client_insurance_company_tertiary,
    client_policy_number_tertiary: clientProfile.client_policy_number_tertiary,
    client_group_number_tertiary: clientProfile.client_group_number_tertiary,
    client_subscriber_name_tertiary: clientProfile.client_subscriber_name_tertiary,
    client_insurance_type_tertiary: clientProfile.client_insurance_type_tertiary,
    client_subscriber_dob_tertiary: clientProfile.client_subscriber_dob_tertiary,
    client_subscriber_relationship_tertiary: clientProfile.client_subscriber_relationship_tertiary,
    client_planlength: clientProfile.client_planlength,
    client_treatmentfrequency: clientProfile.client_treatmentfrequency,
    client_problem: clientProfile.client_problem,
    client_treatmentgoal: clientProfile.client_treatmentgoal,
    client_primaryobjective: clientProfile.client_primaryobjective,
    client_secondaryobjective: clientProfile.client_secondaryobjective,
    client_tertiaryobjective: clientProfile.client_tertiaryobjective,
    client_intervention1: clientProfile.client_intervention1,
    client_intervention2: clientProfile.client_intervention2,
    client_intervention3: clientProfile.client_intervention3,
    client_intervention4: clientProfile.client_intervention4,
    client_intervention5: clientProfile.client_intervention5,
    client_intervention6: clientProfile.client_intervention6,
    client_nexttreatmentplanupdate: clientProfile.client_nexttreatmentplanupdate,
    client_privatenote: clientProfile.client_privatenote,
    client_appearance: clientProfile.client_appearance,
    client_attitude: clientProfile.client_attitude,
    client_behavior: clientProfile.client_behavior,
    client_speech: clientProfile.client_speech,
    client_affect: clientProfile.client_affect,
    client_thoughtprocess: clientProfile.client_thoughtprocess,
    client_perception: clientProfile.client_perception,
    client_orientation: clientProfile.client_orientation,
    client_memoryconcentration: clientProfile.client_memoryconcentration,
    client_insightjudgement: clientProfile.client_insightjudgement,
    client_mood: clientProfile.client_mood,
    client_substanceabuserisk: clientProfile.client_substanceabuserisk,
    client_suicidalideation: clientProfile.client_suicidalideation,
    client_homicidalideation: clientProfile.client_homicidalideation,
    client_functioning: clientProfile.client_functioning,
    client_prognosis: clientProfile.client_prognosis,
    client_progress: clientProfile.client_progress,
    client_sessionnarrative: clientProfile.client_sessionnarrative,
    client_medications: clientProfile.client_medications,
    client_personsinattendance: clientProfile.client_personsinattendance,
    client_currentsymptoms: clientProfile.client_currentsymptoms,
    client_vacoverage: clientProfile.client_vacoverage,
    client_champva: clientProfile.client_champva,
    client_tricare_beneficiary_category: clientProfile.client_tricare_beneficiary_category,
    client_tricare_sponsor_name: clientProfile.client_tricare_sponsor_name,
    client_tricare_sponsor_branch: clientProfile.client_tricare_sponsor_branch,
    client_tricare_sponsor_id: clientProfile.client_tricare_sponsor_id,
    client_tricare_plan: clientProfile.client_tricare_plan,
    client_tricare_region: clientProfile.client_tricare_region,
    client_tricare_policy_id: clientProfile.client_tricare_policy_id,
    client_tricare_has_referral: clientProfile.client_tricare_has_referral,
    client_tricare_referral_number: clientProfile.client_tricare_referral_number,
    client_recentdischarge: clientProfile.client_recentdischarge,
    client_branchOS: clientProfile.client_branchOS,
    client_disabilityrating: clientProfile.client_disabilityrating,
    client_relationship: clientProfile.client_relationship,
    client_veteran_relationship: clientProfile.client_veteran_relationship,
    client_situation_explanation: clientProfile.client_situation_explanation,
    client_mental_health_referral: clientProfile.client_mental_health_referral,
    client_other_insurance: clientProfile.client_other_insurance,
    client_champva_agreement: clientProfile.client_champva_agreement,
    client_tricare_insurance_agreement: clientProfile.client_tricare_insurance_agreement,
    hasMoreInsurance: clientProfile.hasMoreInsurance,
    client_has_even_more_insurance: clientProfile.client_has_even_more_insurance,
  };
};
